name: kobi
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  pluto_grid: ^5.4.9
  intl: ^0.17.0
  go_router: ^6.2.0
  provider: ^6.0.5
  url_strategy: ^0.2.0
  easy_localization: ^3.0.1
  shared_preferences: ^2.0.18

  #Firebase    
  cloud_firestore: ^4.4.2
  firebase_core: ^2.7.1
  firebase_storage: ^11.0.14
  firebase_ui_auth: ^1.1.16
  firebase_auth: ^4.2.10
  firebase_dynamic_links: ^5.0.16
  cloud_firestore_odm: ^1.0.0-dev.49
  json_annotation: ^4.8.0
  email_validator: ^2.0.1
  firebase_ui_localizations: ^1.2.0
  firebase_ui_oauth: ^1.1.16
  firebase_ui_oauth_google: ^1.0.23


  flutter_svg: ^1.1.1
  rxdart: ^0.27.7
  path_provider: ^2.0.12


  
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.1.6
  flutter_lints: ^1.0.4
  flutter_launcher_icons: "^0.11.0"
  build_runner: ^2.3.3
  cloud_firestore_odm_generator: ^1.0.0-dev.49
  json_serializable: ^6.6.1
  flutter_gen_runner: ^5.2.0


flutter:
  uses-material-design: true
  assets:
    - assets/sources/
    - assets/test/    
    - assets/translations/
  #- assets/translations/en.json

fonts:
  - family: SocialIcons
    fonts:
      - asset: packages/firebase_ui_auth/fonts/SocialIcons.ttf


flutter_native_splash:
  color: "#000000"
  image: assets/sources/splash.jpeg

flutter_icons:
  android: false
  ios: false
  image_path: "assets/sources/logo.jpeg"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/sources/logo.jpeg"
    background_color: "202020"
    theme_color: "0175C2"
  windows:
    generate: true
    image_path: "assets/sources/logo.jpeg"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/sources/logo.jpeg"